// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMo4ZpxKO29e-gFyjiuQX5HDT-0K3vzwk',
    appId: '1:94387615592:web:a5cbea61597801ff8b88dd',
    messagingSenderId: '94387615592',
    projectId: 'smartdoorbellcpe461',
    authDomain: 'smartdoorbellcpe461.firebaseapp.com',
    storageBucket: 'smartdoorbellcpe461.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8LNWtWn1gIATo8RoqC8xUo-ZTPcHVmpI',
    appId: '1:94387615592:android:2747a359c25ed0e68b88dd',
    messagingSenderId: '94387615592',
    projectId: 'smartdoorbellcpe461',
    storageBucket: 'smartdoorbellcpe461.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVRFydbWtI0qwZKsFeMtKao8jh9IotFZ4',
    appId: '1:94387615592:ios:93d0fb608a5058388b88dd',
    messagingSenderId: '94387615592',
    projectId: 'smartdoorbellcpe461',
    storageBucket: 'smartdoorbellcpe461.firebasestorage.app',
    iosBundleId: 'com.example.smartDoorbell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVRFydbWtI0qwZKsFeMtKao8jh9IotFZ4',
    appId: '1:94387615592:ios:93d0fb608a5058388b88dd',
    messagingSenderId: '94387615592',
    projectId: 'smartdoorbellcpe461',
    storageBucket: 'smartdoorbellcpe461.firebasestorage.app',
    iosBundleId: 'com.example.smartDoorbell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMo4ZpxKO29e-gFyjiuQX5HDT-0K3vzwk',
    appId: '1:94387615592:web:7533023c64ffc5be8b88dd',
    messagingSenderId: '94387615592',
    projectId: 'smartdoorbellcpe461',
    authDomain: 'smartdoorbellcpe461.firebaseapp.com',
    storageBucket: 'smartdoorbellcpe461.firebasestorage.app',
  );

}